-- YOUR CODE GOES HERE
-- CREATE YOUR DATABASE
-- CREATE YOUR TABLES
-- ADD RECORDS TO YOUR TABLE

CREATE DATABASE cowlist;

USE cowlist;

CREATE TABLE cows (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cowName VARCHAR(20),
  cowDescription VARCHAR(200)
);